// flow-typed signature: 0070e4c3fc83bd5e9e582d82e16d4a91
// flow-typed version: <<STUB>>/react-native-safe-area-context_v0.3.6/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-safe-area-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-safe-area-context' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-safe-area-context/lib/commonjs/index' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/NativeSafeAreaView' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/NativeSafeAreaView.web' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/commonjs/SafeArea.types' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/index' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/NativeSafeAreaView' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/NativeSafeAreaView.web' {
  declare module.exports: any;
}

declare module 'react-native-safe-area-context/lib/module/SafeArea.types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-safe-area-context/lib/commonjs/index.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/index'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/NativeSafeAreaView.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/NativeSafeAreaView'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/NativeSafeAreaView.web.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/NativeSafeAreaView.web'>;
}
declare module 'react-native-safe-area-context/lib/commonjs/SafeArea.types.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/commonjs/SafeArea.types'>;
}
declare module 'react-native-safe-area-context/lib/module/index.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/index'>;
}
declare module 'react-native-safe-area-context/lib/module/NativeSafeAreaView.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/NativeSafeAreaView'>;
}
declare module 'react-native-safe-area-context/lib/module/NativeSafeAreaView.web.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/NativeSafeAreaView.web'>;
}
declare module 'react-native-safe-area-context/lib/module/SafeArea.types.js' {
  declare module.exports: $Exports<'react-native-safe-area-context/lib/module/SafeArea.types'>;
}
